export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_PUBLIC_INFO = 'FETCH_PUBLIC_INFO';
export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES';
export const FETCH_CHARACTER_SKILLS = 'FETCH_CHARACTER_SKILLS';
export const FETCH_ALL_SKILLS = 'FETCH_ALL_SKILLS';

